version: "3.8"
services:
  web:
    build: .
    ports:
      - "8000:8000"  # Django приложение
      - "8002:8002"  # Метрики
    environment:
      - ENV=production
    depends_on:
      - prometheus

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml